services:
  master_db:
    image: pgvector/pgvector:pg16
    container_name: infra-master_db-1
    environment:
      POSTGRES_DB: master
      POSTGRES_USER: insightiq
      POSTGRES_PASSWORD: insightiq
    ports:
      - "5433:5432"
    volumes:
      - master_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U insightiq -d master"]
      interval: 5s
      timeout: 5s
      retries: 5

  tenant_db:
    image: pgvector/pgvector:pg16
    container_name: infra-tenant_db-1
    environment:
      POSTGRES_DB: brand_intelligence
      POSTGRES_USER: insightiq
      POSTGRES_PASSWORD: insightiq
    ports:
      - "5432:5432"
    volumes:
      - tenant_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U insightiq -d brand_intelligence"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ../services/api
    container_name: infra-api-1
    depends_on:
      master_db:
        condition: service_healthy
      tenant_db:
        condition: service_healthy
    environment:
      MASTER_DB_URL: postgresql+asyncpg://insightiq:insightiq@master_db:5432/master
    ports:
      - "8000:8000"
  
  dbt:
    build: ../services/dbt
    container_name: infra-dbt-1
    depends_on:
      - tenant_db
    volumes:
      - ../services/dbt:/dbt
    working_dir: /dbt
    entrypoint: ["dbt"]


volumes:
  master_data:
  tenant_data:
